sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t asm06/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asm06/react-test npm test

after_success:
  - docker build -t asm06/multi-client ./client
  - docker build -t asm06/multi-nginx ./nginx
  - docker build -t asm06/multi-server ./server
  - docker build -t asm06/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  - docker push asm06/multi-client
  - docker push asm06/multi-nginx
  - docker push asm06/multi-server
  - docker push asm06/multi-worker
