sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t asm06-poc/react-test -f .client/Dockerfile.dev .

script:
  - docker run -e CI=true asm06-poc/react-test npm run test

after_success:
  - docker build -t asm06-poc/multi-client ./client
  - docker build -t asm06-poc/multi-nginx ./nginx
  - docker build -t asm06-poc/multi-server ./server
  - docker build -t asm06-poc/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin